server:
  servlet:
    context-path: /
  port: 8081
  undertow:
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: springboot-redis-demo
  redis:
    host: localhost
    port: 6379
    database: 1
    password:
    client-name: test
    client-type: jedis
    jedis:
      pool:
        max-active: 8
        min-idle: 2
        max-wait: 1s

    connect-timeout: 3000ms