server:
  servlet:
    application-display-name: sub-pub-demo
    context-path: /
  port: 8083
spring:
  application:
    name: sub-pub-demo
  redis:
    connect-timeout: 5000ms
    client-name: redis-demo
    client-type: lettuce
    lettuce:
      pool:
        max-idle: 5
        min-idle: 1
        max-active: 5
        max-wait: 5s
    host: localhost
    port: 6379
    database: 0